export const Colors = {
  light: {
    text: "#1A1A1A",
    background: "#FFFFFF",
    tint: "#2F95DC",
    tabIconDefault: "#9CA3AF",
    tabIconSelected: "#2F95DC",
    icon: "#1A1A1A",
    cardBackground: "#F5F5F5",
    border: "#E5E7EB",
    success: "#4CAF50",
    error: "#FF5252",
  },
  dark: {
    text: "#FFFFFF",
    background: "#121212",
    tint: "#5FA9E6",
    tabIconDefault: "#6B7280",
    tabIconSelected: "#5FA9E6",
    icon: "#FFFFFF",
    cardBackground: "#1E1E1E",
    border: "#2D2D2D",
    success: "#66BB6A",
    error: "#FF5252",
  },
} as const;
